FROM python:3.11-slim

WORKDIR /app

RUN apt update -y && apt install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel && pip install -r requirements.txt

COPY . .

EXPOSE 5153

CMD ["python", "app.py"]
